name: Publish Package to npm
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI for testing
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # needed for npm provenance
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        env:
          CI: true
        run: npm test # Ensure your test script handles the CI environment variable
      - name: Update all package.json files with tag version
        if: startsWith(github.ref, 'refs/tags/') # Only run for tag pushes
        run: |
          TAG="${GITHUB_REF#refs/tags/v}"
          npm version "$TAG" --no-git-tag-version # Update version without creating a new git tag
          cd src/conduit_mcp_server
          npm version "$TAG" --no-git-tag-version
          cd ../..

      - name: Get latest tag
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update version badge in README
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${{ steps.get_tag.outputs.TAG }}
          sed -i "s/version-[0-9]\+\.[0-9]\+\.[0-9]\+-blue\.svg/version-${VERSION}-blue.svg/g" readme.md
          sed -i "s/claude-talk-to-figma-mcp/conduit/g" readme.md

      - name: Commit version and badge updates
        if: startsWith(github.ref, 'refs/tags/')
        id: commit_changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add readme.md package.json src/conduit_mcp_server/package.json
          git commit -m "Update version badge and package.json to v${{ steps.get_tag.outputs.TAG }}"

      - name: Checkout main branch
        if: startsWith(github.ref, 'refs/tags/')
        run: git checkout main

      - name: Cherry-pick commit from tag workflow
        if: startsWith(github.ref, 'refs/tags/')
        run: git cherry-pick ${{ github.sha }}

      - name: Push changes to main
        if: startsWith(github.ref, 'refs/tags/')
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/') # Only run for tag pushes
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
