name: Publish Package to npm
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI for testing
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # needed for npm provenance
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build package
        run: bun run build:all
      - name: Run tests
        run: bun run test
      - name: List dist contents
        run: ls -R dist
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/') # Only run for tag pushes
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
